"""crear tablas productos tipo_productos u_medidas

Revision ID: 132c5621ef50
Revises: b2f4208d1bbf
Create Date: 2026-02-22 16:11:55.395211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132c5621ef50'
down_revision: Union[str, None] = 'b2f4208d1bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipo_productos_id'), 'tipo_productos', ['id'], unique=False)
    op.create_table('u_medidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_u_medidas_id'), 'u_medidas', ['id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=150), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('tipo_maquina_id', sa.Integer(), nullable=False),
    sa.Column('tipo_producto_id', sa.Integer(), nullable=False),
    sa.Column('u_medida_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_maquina_id'], ['tipo_maquinas.id'], ),
    sa.ForeignKeyConstraint(['tipo_producto_id'], ['tipo_productos.id'], ),
    sa.ForeignKeyConstraint(['u_medida_id'], ['u_medidas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_u_medidas_id'), table_name='u_medidas')
    op.drop_table('u_medidas')
    op.drop_index(op.f('ix_tipo_productos_id'), table_name='tipo_productos')
    op.drop_table('tipo_productos')
    # ### end Alembic commands ###
