"""crear tablas materia prima

Revision ID: 250ca6cd4f9d
Revises: 3e7997505f9e
Create Date: 2026-03-04 17:23:36.343163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '250ca6cd4f9d'
down_revision: Union[str, None] = '3e7997505f9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materia_prima_tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_materia_prima_tipo_id'), 'materia_prima_tipo', ['id'], unique=False)
    op.create_table('materia_prima',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('oc', sa.String(length=100), nullable=True),
    sa.Column('factura', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materia_prima_id'), 'materia_prima', ['id'], unique=False)
    op.create_table('materia_prima_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('mp_tipo_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colores.id'], ),
    sa.ForeignKeyConstraint(['mp_id'], ['materia_prima.id'], ),
    sa.ForeignKeyConstraint(['mp_tipo_id'], ['materia_prima_tipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materia_prima_detalle_id'), 'materia_prima_detalle', ['id'], unique=False)
    op.alter_column('ordenes_produccion', 'fecha',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('ordenes_produccion', 'producto_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ordenes_produccion', 'densidad',
               existing_type=mysql.ENUM('alta', 'baja', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=False)
    op.alter_column('ordenes_produccion', 'color_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ordenes_produccion', 'ancho',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ordenes_produccion', 'espesor',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ordenes_produccion', 'estado',
               existing_type=mysql.ENUM('pendiente', 'en_produccion', 'completada', 'cancelada', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=False)
    op.create_foreign_key(None, 'ordenes_produccion', 'empresas', ['empresa_id'], ['id'])
    op.create_foreign_key(None, 'ordenes_produccion', 'productos', ['producto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ordenes_produccion', type_='foreignkey')
    op.drop_constraint(None, 'ordenes_produccion', type_='foreignkey')
    op.alter_column('ordenes_produccion', 'estado',
               existing_type=mysql.ENUM('pendiente', 'en_produccion', 'completada', 'cancelada', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=True)
    op.alter_column('ordenes_produccion', 'espesor',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('ordenes_produccion', 'ancho',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('ordenes_produccion', 'color_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('ordenes_produccion', 'densidad',
               existing_type=mysql.ENUM('alta', 'baja', charset='utf8mb4', collation='utf8mb4_0900_ai_ci'),
               nullable=True)
    op.alter_column('ordenes_produccion', 'producto_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('ordenes_produccion', 'fecha',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index(op.f('ix_materia_prima_detalle_id'), table_name='materia_prima_detalle')
    op.drop_table('materia_prima_detalle')
    op.drop_index(op.f('ix_materia_prima_id'), table_name='materia_prima')
    op.drop_table('materia_prima')
    op.drop_index(op.f('ix_materia_prima_tipo_id'), table_name='materia_prima_tipo')
    op.drop_table('materia_prima_tipo')
    # ### end Alembic commands ###
