"""crear tablas selladora

Revision ID: 3cafdb40cd7b
Revises: d10df6891bd9
Create Date: 2026-03-19 15:34:54.256351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cafdb40cd7b'
down_revision: Union[str, None] = 'd10df6891bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('op_selladora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('ancho', sa.Float(), nullable=False),
    sa.Column('espesor', sa.Float(), nullable=False),
    sa.Column('largo', sa.Float(), nullable=False),
    sa.Column('unidades', sa.Integer(), nullable=False),
    sa.Column('kilos', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colores.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_op_selladora_id'), 'op_selladora', ['id'], unique=False)
    op.create_table('produccion_selladora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('op_id', sa.Integer(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('turno', sa.String(length=10), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], ),
    sa.ForeignKeyConstraint(['op_id'], ['op_selladora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produccion_selladora_id'), 'produccion_selladora', ['id'], unique=False)
    op.create_table('produccion_selladora_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produccion_selladora_id', sa.Integer(), nullable=False),
    sa.Column('detalle_extrusora_id', sa.Integer(), nullable=False),
    sa.Column('q_paquetes', sa.Integer(), nullable=False),
    sa.Column('q_unidades_por_paquete', sa.Integer(), nullable=False),
    sa.Column('unidades', sa.Integer(), nullable=False),
    sa.Column('kilos', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['detalle_extrusora_id'], ['detalle_produccion_extrusora.id'], ),
    sa.ForeignKeyConstraint(['produccion_selladora_id'], ['produccion_selladora.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detalle_extrusora_id')
    )
    op.create_index(op.f('ix_produccion_selladora_detalle_id'), 'produccion_selladora_detalle', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produccion_selladora_detalle_id'), table_name='produccion_selladora_detalle')
    op.drop_table('produccion_selladora_detalle')
    op.drop_index(op.f('ix_produccion_selladora_id'), table_name='produccion_selladora')
    op.drop_table('produccion_selladora')
    op.drop_index(op.f('ix_op_selladora_id'), table_name='op_selladora')
    op.drop_table('op_selladora')
    # ### end Alembic commands ###
