"""actualizar tablas produccion con calibre ancho espesor

Revision ID: 46214e0cce68
Revises: 708e6a4658ba
Create Date: 2026-02-22 19:14:50.311079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46214e0cce68'
down_revision: Union[str, None] = '708e6a4658ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
