"""cambiar producto_id por tipo_producto_id en OP

Revision ID: 6239f5bfc336
Revises: afa42f11071a
Create Date: 2026-02-25 20:47:50.303773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6239f5bfc336'
down_revision: Union[str, None] = 'afa42f11071a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes_produccion', sa.Column('tipo_producto_id', sa.Integer(), nullable=True))
    op.drop_constraint('ordenes_produccion_ibfk_3', 'ordenes_produccion', type_='foreignkey')
    op.create_foreign_key(None, 'ordenes_produccion', 'tipo_productos', ['tipo_producto_id'], ['id'])
    op.drop_column('ordenes_produccion', 'producto_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes_produccion', sa.Column('producto_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ordenes_produccion', type_='foreignkey')
    op.create_foreign_key('ordenes_produccion_ibfk_3', 'ordenes_produccion', 'productos', ['producto_id'], ['id'])
    op.drop_column('ordenes_produccion', 'tipo_producto_id')
    # ### end Alembic commands ###
