"""crear tablas maquinas y tipo_maquinas

Revision ID: 73e430cca7ce
Revises: 64dedec89c86
Create Date: 2026-02-22 06:40:40.044658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e430cca7ce'
down_revision: Union[str, None] = '64dedec89c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
