"""actualizar tablas produccion con calibre ancho espesor

Revision ID: 92d2b49caecc
Revises: 46214e0cce68
Create Date: 2026-02-22 19:19:45.371064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d2b49caecc'
down_revision: Union[str, None] = '46214e0cce68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
