"""actualizar tablas produccion con calibre ancho espesor

Revision ID: afa42f11071a
Revises: 92d2b49caecc
Create Date: 2026-02-22 19:21:32.616498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa42f11071a'
down_revision: Union[str, None] = '92d2b49caecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordenes_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maquina_id', sa.Integer(), nullable=False),
    sa.Column('kilos_a_producir', sa.Float(), nullable=False),
    sa.Column('lote', sa.String(length=100), nullable=False),
    sa.Column('calibre', sa.Enum('alta', 'baja', name='calibreenum'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'en_produccion', 'completada', 'cancelada', name='estadoopenum'), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('oc_cliente', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['maquina_id'], ['maquinas.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_produccion_id'), 'ordenes_produccion', ['id'], unique=False)
    op.create_table('produccion_extrusora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('op_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('turno', sa.Enum('manana', 'tarde', 'noche', name='turnoenum'), nullable=False),
    sa.ForeignKeyConstraint(['op_id'], ['ordenes_produccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produccion_extrusora_id'), 'produccion_extrusora', ['id'], unique=False)
    op.create_table('detalle_produccion_extrusora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produccion_extrusora_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.Column('numero_rollo', sa.Integer(), nullable=False),
    sa.Column('ancho', sa.Integer(), nullable=False),
    sa.Column('espesor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produccion_extrusora_id'], ['produccion_extrusora.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_produccion_extrusora_id'), 'detalle_produccion_extrusora', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_produccion_extrusora_id'), table_name='detalle_produccion_extrusora')
    op.drop_table('detalle_produccion_extrusora')
    op.drop_index(op.f('ix_produccion_extrusora_id'), table_name='produccion_extrusora')
    op.drop_table('produccion_extrusora')
    op.drop_index(op.f('ix_ordenes_produccion_id'), table_name='ordenes_produccion')
    op.drop_table('ordenes_produccion')
    # ### end Alembic commands ###
