"""crear tablas maquinas y tipo_maquinas

Revision ID: b2f4208d1bbf
Revises: b9fd5e235979
Create Date: 2026-02-22 06:57:01.219306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f4208d1bbf'
down_revision: Union[str, None] = 'b9fd5e235979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_maquinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipo_maquinas_id'), 'tipo_maquinas', ['id'], unique=False)
    op.create_table('maquinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('url_foto', sa.String(length=255), nullable=True),
    sa.Column('tipo_maquina_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_maquina_id'], ['tipo_maquinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maquinas_id'), 'maquinas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maquinas_id'), table_name='maquinas')
    op.drop_table('maquinas')
    op.drop_index(op.f('ix_tipo_maquinas_id'), table_name='tipo_maquinas')
    op.drop_table('tipo_maquinas')
    # ### end Alembic commands ###
