"""crear tablas maquinas y tipo_maquinas

Revision ID: b5682670b681
Revises: 73e430cca7ce
Create Date: 2026-02-22 06:50:09.848645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5682670b681'
down_revision: Union[str, None] = '73e430cca7ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
