"""crear tablas maquinas y tipo_maquinas

Revision ID: b9fd5e235979
Revises: b5682670b681
Create Date: 2026-02-22 06:54:41.139740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9fd5e235979'
down_revision: Union[str, None] = 'b5682670b681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
