"""reestructura produccion + materia prima

Revision ID: d10df6891bd9
Revises: 250ca6cd4f9d
Create Date: 2026-03-10 20:18:18.843939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10df6891bd9'
down_revision: Union[str, None] = '250ca6cd4f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
