"""crear tabla empresas

Revision ID: d815acfd5086
Revises: 69e9d667c01e
Create Date: 2026-02-22 18:14:32.091400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd815acfd5086'
down_revision: Union[str, None] = '69e9d667c01e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_empresa', sa.Enum('cliente', 'proveedor', name='tipoempresaenum'), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
