"""actualizar tablas produccion con calibre ancho espesor

Revision ID: e241d8fddd62
Revises: d815acfd5086
Create Date: 2026-02-22 19:11:04.175310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e241d8fddd62'
down_revision: Union[str, None] = 'd815acfd5086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
